const mongojs = require('mongojs')

module.exports = [
  {
    _id: mongojs.ObjectId('000000000000000000000002'),
    firstname: 'John',
    lastname: 'Doe',
    isUsePassport: true,
    nationalId: '7021541772072',
    phoneNumber: '081111111',
    homeNumber: '32',
    homeMoo: '5',
    homeMooban: '-',
    homePostalCode: '80130',
    homeSubDistrict: 'สามตำบล',
    homeDistrict: 'จุฬาภรณ์',
    homeProvince: 'นครศรีธรรมราช',
    allergies: ['NO_BEAN', 'NO_CHICKEN'],
    diseases: ['GOUT', 'DIABETES'],
    members: [
      {
        isUsePassport: true,
        firstname: 'Siri',
        lastname: 'Doe',
        nationalId: '7021541772111',
        allergies: ['NO_PORK', 'NO_CHICKEN'],
        diseases: ['HEART_DISEASE'],
      },
      {
        isUsePassport: true,
        firstname: 'Jina',
        lastname: 'Doe',
        nationalId: '7021541772222',
        allergies: ['NO_SEA_FOOD', 'NO_MILK'],
        diseases: ['BLOOD_PRESSURE'],
      },
    ],
  },
  {
    _id: mongojs.ObjectId('000000000000000000000003'),
    firstname: 'สามชาย',
    lastname: 'ยินดี',
    isUsePassport: false,
    nationalId: '1281036360039',
    phoneNumber: '081111112',
    homeNumber: '11',
    homeMoo: '4',
    homeMooban: 'ทานตะวัน',
    homePostalCode: '90110',
    homeSubDistrict: 'คอหงส์',
    homeDistrict: 'หาดใหญ่',
    homeProvince: 'สงขลา',
    allergies: ['NO_MEAT'],
    diseases: ['HEART_DISEASE'],
    members: [
      {
        isUsePassport: false,
        firstname: 'สมหมาย',
        lastname: 'ยินดี',
        nationalId: '7021541772555',
        allergies: ['NO_SEA_FOOD'],
        diseases: ['BLOOD_PRESSURE'],
      },
    ],
  },
]
